using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Burst.SWF
{
    public enum SWFTagType
    {
        Unknown = -1,
        End,
        ShowFrame,
        DefineShape,
        PlaceObject = 4,
        RemoveObject,
        DefineBits,
        DefineButton,
        JPEGTables,
        SetBackGroundColor,
        DefineFont,
        DefineText,
        DoAction,
        DefineFontInfo,
        DefineSound,
        StartSound,
        DefineButtonSound = 17,
        SoundStreamHead,
        SoundStreamBlock,
        DefineBitsLossless,
        DefineBitsJPEG2,
        DefineShape2,
        DefineButtonCxform,
        Protect,
        PlaceObject2 = 26,
        RemoveObject2 = 28,
        DefineShape3 = 32,
        DefineText2,
        DefineButton2,
        DefineBitsJPEG3,
        DefineBitsLossless2,
        DefineEditText,
        DefineSprite = 39,
        FrameLabel = 43,
        SoundStreamHead2 = 45,
        DefineMorphShape,
        DefineFont2 = 48,
        ExportAssets = 56,
        ImportAssets,
        EnableDebugger,
        DoInitAction,
        DefineVideoStream,
        VideoFrame,
        DefineFontInfo2,
        EnableDebugger2 = 64,
        ScriptLimits,
        SetTabIndex,
        FileAttributes = 69,
        PlaceObject3,
        ImportAssets2,
        DefineFontAlignZones = 73,
        CSMTextSettings,
        DefineFont3,
        SymbolClass,
        MetaData,
        DefineScalingGrid,
        DoABC = 82,
        DefineShape4,
        DefineMorphShape2,
        DefineSceneAndFrameLabelData = 86,
        DefineBinaryData,
        DefineFontName,
        StartSound2,
        DefineBitsJPEG4,
        DefineFont4
    }
}
